const samplePreApprovalData = {
  offerAmount: '$350000',
  downPayment: '$20000',
  taxes: '$10',
  annualtaxes: '$120',
  insurance: '$10',
  annualInsurance: '$120',
  HOA: '$10',
  annualHOA: '$120',
  mi: '$10',
  annualMI: '$120',
  sellerConcession: '$100',
  address: '13th Street',
  city: 'New York',
  state: 'NY',
  zip: 10036,
  baseLoanAmount: '$330000',
  totalLoanAmount: '$350000',
  estimatedMonthlyPayment: '$2000.20',
  LTV: 80,
  estimatedCashToClose: '$3000.15',
  loanMonthlyPayment: '$1000.02',
  downloadCount: 0,
  //Approval Data
  fileId: '12345678',
  expiresOn: Date.now(),
  additionalComments: 'Additional Comments',
  annualHazardInsurance: 30,
  annualTaxRate: 20,
  lockTaxRate: 20,
  buyer: {
    name: 'Test Buyer',
    maritalStatus: 'married',
    creditScore: 750,
    isRelyingOnProperty: true,
    isRelyingOnSellerConcession: true,
    isRelyingOnDownPayment: true,
    isBuyerProvideHUD: 'yes',
    isBuyerCompletedDiscussion: 'yes',
    isTriMergedResidentialCreditReport: 'yes',
    address: '13th Street',
    city: 'New York',
    state: 'NY',
    zip: 10036,
  },
  loan: {
    type: 'FHA',
    typeFormatted: 'FHA',
    occupancy: 'PrimaryResidence',
    occupancyFormatted: 'Primary Residence',
    propertyType: 'singleFamily',
    propertyTypeFormatted: 'Single Family',
    term: 300,
    amount: 350000,
    interestRate: 5,
    monthlyInterestPayment: 2200,
    totalMonthlyInterestPayment: 500,
    rateType: 'fixedInterestRate',
    maxMonthlyPayment: 2500,
    maxMonthlyPaymentType: '$',
    maxDownPayment: 25000,
    maxDownPaymentType: '$',
    minDownPayment: 10000,
    minDownPaymentType: '$',
    discountPoints: 200,
    closingCosts: 3000,
    hideCloseToClose: false,
    creditReviewed: true,
    assetReviewed: true,
    incomeReviewed: false,
    taxReturnsReviewed: false,
    dulpReviewed: false,
    homeSaleContingency: true,
    otherContingencies: 'other contingency',
    lenderCredit: 500,
    conventionalType: 'monthly',
    splitPremium: 10,
    MIRate: 2,
    monthlyAmount: 200,
    upfrontAmount: 2100,
    escrows: true,
  },
  lender: {
    name: 'Lender Name',
    company: 'Company Name',
    license: 1234657,
    NMLS: 123467,
    address: '13th Street',
    city: 'New York',
    state: 'NY',
    zip: 10036,
    email: 'lender@email.com',
    phone: 0123456789,
    fax: 0123456789,
    signature: "Lender's Signature",
    signatureDate: Date.now(),
  },
  documentation: {
    payStubs: 'yes',
    W2s: 'yes',
    personalTaxReturns: 'yes',
    corporateTaxReturns: 'yes',
    downPayment: 'yes',
    gift: 'yes',
    credit: 'yes',
    otherName: 'yes',
    other: 'yes',
  },
  borrower: {
    name: 'Test borrower',
    phone: 0123456789,
    email: 'borrower@email.com',
    formattedPhone: '(000) 111-2345',
    loanOfficerId: {
      name: 'Lender Name',
      email: 'lender@email.com',
      phone: 01234567890,
      NMLS: 1234567,
      companyId: {
        name: 'Champs',
        NMLS: 1234567,
        fullAddress: '10575 68th Ave. Suite C2 Seminole, Florida',
        _logo: ''
      },
    },
  },
  fullAddress: `13th Street New York, NY 10036`,
  currentDate: 'Nov 10 2022',
  currentMonth: 'Nov 11 2022',
  expiresOnDate: 'Nov 11 2022',
};

module.exports = {
  samplePreApprovalData,
};
